DB_USERNAME: ""
DB_PASSWORD: ""

ADMIN_USER: "admin"
ADMIN_PASSWORD: "1234"

STRIPE_PUBLISHABLE_KEY: "pk_test_123"
STRIPE_SECRET_KEY: "sk_test_123"

MAILGUN_SMTP_PORT: "XXX"
MAILGUN_SMTP_SERVER: "XXX"
MAILGUN_SMTP_LOGIN: "XXX"
MAILGUN_SMTP_PASSWORD: "XXX"
MAILGUN_DOMAIN: "XXX"

DEVELOPMENT_INTERCEPT_EMAIL: "foo@example.com"